### ISSUE TITLE
Licensing and Ethicism

### ISSUE THREAD

**Issue by marc2332** [prasadbobby/EduCode#1]
Hello

I am the creator of [Graviton](https://github.com/Graviton-Code-Editor/Graviton-App)

I just saw this repo, and I am here to let you know you are violating Graviton's license (MIT).

You can read about it here: https://mit-license.org/
Original license: https://github.com/Graviton-Code-Editor/Graviton-App/blob/master/LICENSE.md

Also, there are a few things I really dislike:

* You renamed all "Made by Marc Espín" to your name, there is not even a single mention to the original project, me, or any contributor.

   This includes all package.json, About Dialog, etc...
* You hid the contributors sub menu
![imagen](https://user-images.githubusercontent.com/38158676/94201473-53b68a00-febc-11ea-8252-8834a74702e4.png)
Code: https://github.com/prasadbobby/EduCode/blob/5a1214cdd1879b8fb649d3ed7b7af0f1d7469aa2/src/javascript/defaults/menus.ts#L324

* You added a new menu just for donating: 
![imagen](https://user-images.githubusercontent.com/38158676/94201414-400b2380-febc-11ea-9a01-88595370c2ef.png)
Code: https://github.com/prasadbobby/EduCode/blob/5a1214cdd1879b8fb649d3ed7b7af0f1d7469aa2/src/javascript/defaults/menus.ts#L272
How it looks: 
![imagen](https://user-images.githubusercontent.com/38158676/94202015-274f3d80-febd-11ea-821b-110f850c1997.png)

So, you literally took the work of 37 people and me, rebranded the whole thing, added a donate button, removed all mentions to me or any contributor and removed the license.

I hope you fix this 👍🏻

**Comment by EnderDev** [comment]
This is really disgusting, I can’t believe people think they can just get away with this...

**Comment by dragonDScript** [comment]
My project had this issue too, when I saw this, I fixed it 👍
Hope this person fixes this.

**Comment by prasadbobby** [comment]
yes completely fixed
